export { default as w } from "./w.png";
export { default as u } from "./u.png";
export { default as b } from "./b.png";
export { default as r } from "./r.png";
export { default as g } from "./g.png";
export { default as m } from "./m.png";
export { default as a } from "./a.png";
export { default as c } from "./c.png";
export { default as l } from "./L.png";
